service: proyIndra

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource:
            - Fn::GetAtt: [ClientTable, Arn]

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: 'node16'
    external: []

functions:
  createClient:
    handler: src/handlers/createClientHandler.handler
    events:
      - httpApi:
          path: /client
          method: POST
  getClient:
    handler: src/handlers/getClientHandler.handler
    events:
      - httpApi:
          path: /client/{id}
          method: GET
  getSwapiPlanet:
    handler: src/handlers/getSwapiPlanetHandler.handler
    events:
      - httpApi:
          path: /getSwapiPlanet
          method: GET

plugins:
  - serverless-esbuild
  - serverless-offline

resources:
  Resources:
    ClientTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientTable
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: clientID
            AttributeType: S
        KeySchema:
          - AttributeName: clientID
            KeyType: HASH
