service: proyIndra

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource:
            - Fn::GetAtt: [ClientTable, Arn]

functions:
  createClient:
    handler: src/handler/createClientHandler.handler
    events:
      - httpApi:
          path: /client
          method: POST
  getClient:
    handler: src/handler/getClientHandler.handler
    events:
      - httpApi:
          path: /client/{id}
          method: GET
  getSwapiPlanet:
    handler: src/handler/getSwapiPlanetHandler.handler
    events:
      - httpApi:
          path: /getSwapiPlanet
          method: GET

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    ClientTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientTable
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: clientID
            AttributeType: S
        KeySchema:
          - AttributeName: clientID
            KeyType: HASH
